
//State de productos
export const OBTENER_PRODUCTOS = 'OBTENER_PRODUCTOS'

//State para el pedido
export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO'
export const CONFIRMAR_ORDENAR_PLATILLO = 'CONFIRMAR_ORDENAR_PLATILLO'
export const MOSTRAR_RESUMEN = 'MOSTRAR_RESUMEN'
export const ELIMINAR_PRODUCTO_CARRITO = 'ELIMINAR_PRODUCTO_CARRITO'
export const PEDIDO_ORDENADO = 'PEDIDO_ORDENADO'
export const ORDEN_TERMINADA = 'ORDEN_TERMINADA'