
//State de productos
export const OBTENER_PRODUCTOS = 'OBTENER_PRODUCTOS'

//State para el pedido
export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO'
export const CONFIRMAR_ORDENAR_PLATILLO = 'CONFIRMAR_ORDENAR_PLATILLO'